// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMXVq3G30uMOaVioANj5rmvBO-6qobVuc',
    appId: '1:961182349026:web:042cbb09a44aff10d610bb',
    messagingSenderId: '961182349026',
    projectId: 'newproject-181b8',
    authDomain: 'newproject-181b8.firebaseapp.com',
    databaseURL: 'https://newproject-181b8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newproject-181b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCVybi0KccqPsy7I7lCtV1xOgPl2bcbc',
    appId: '1:961182349026:android:36125b125a4a4668d610bb',
    messagingSenderId: '961182349026',
    projectId: 'newproject-181b8',
    databaseURL: 'https://newproject-181b8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newproject-181b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXcLXcXYrBGNtwPRDl_Nfqg4GOefQ9aeg',
    appId: '1:961182349026:ios:849777a6bbafddc2d610bb',
    messagingSenderId: '961182349026',
    projectId: 'newproject-181b8',
    databaseURL: 'https://newproject-181b8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newproject-181b8.appspot.com',
    iosClientId: '961182349026-blas4t982ceerg9jccca8192io34tinj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXcLXcXYrBGNtwPRDl_Nfqg4GOefQ9aeg',
    appId: '1:961182349026:ios:9d666b0a28bc9dd7d610bb',
    messagingSenderId: '961182349026',
    projectId: 'newproject-181b8',
    databaseURL: 'https://newproject-181b8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newproject-181b8.appspot.com',
    iosClientId: '961182349026-c7qn045mfut27mv762pvhrd2lfm1gkli.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
